import {Play} from "next/font/google";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';


const play = Play({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})


export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ar' }]
}

export const metadata = {
  title: "Otek | Home",
  description: "Generated by create next app",
//   manifest: "/manifest.json", 
};

export default function RootLayout({ children,params }) {
  const lang = params.lang;

  return (
    // <html lang={params.lang} dir={lang === 'ar' ? 'rtl' : 'ltr'}>
    <html lang="en" dir='ltr' className={play.className}>
      <body className={`${play.className} bg-[#f9f7f7] text-[#5d7186]`}>
      {/* <body className={"cu-teal"}> */}
       <NextTopLoader
  color="#308fe8"
  initialPosition={0.08}
  crawlSpeed={200}
  height={5}
  crawl={true}
  showSpinner={true}
  easing="ease"
  speed={200}
  template='<div class="bar" role="bar"><div class="peg"></div></div>
  <div class="loader-background"></div>
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
/>
        {children}
      </body>
    </html>
  );
}
